from pathlib import Path
import pandas as pd

### Load samples.tsv file and obtain list of samples ###
SAMPLE_TABLE = pd.read_csv(config["input"]["sample table"], index_col="sample", sep="\t")
SAMPLE_TABLE.index = SAMPLE_TABLE.index.map(str)  # convert index (samples) to string 
SAMPLES = SAMPLE_TABLE.index.tolist()  # obtain list of samples 

##### Define intermediate/results files/directories #####
scratch_dir = Path(config["scratch directory"])
results_dir = Path(config["results directory"])

Path(scratch_dir).mkdir(exist_ok=True, parents=True)
Path(results_dir).mkdir(exist_ok=True, parents=True)

scratch_dict = {
    "QC": scratch_dir / "QC",  # QC: read trimming/filtering
    "genome_index_done": scratch_dir / "genome_index_done.txt",  # index genome 
    "read_mapping": scratch_dir / "read_mapping",  # read mapping 
    "mapping_stats": scratch_dir / "mapping_stats",  # mapping statistics
}

results_dict = {
    "final": results_dir / "MappingCov.xlsx"
}

##### Define the file files to generate #####
rule all:
    input:
        results_dict["final"],

##### Import Snakemake Rules #####
for smk_file in Path('workflow/rules').glob('*smk'):
    include: str(smk_file).replace('workflow/', '') 







